/*
	* Automatically generated by make menuconfig: don't edit
 */

#undef  CONFIG_RTL8195BHP 
#define CONFIG_RTL8195BHP 1
	 
#define CONFIG_WIFI_NORMAL 1
#define CONFIG_NETWORK 1

#define PLATFORM_FREERTOS 1
#define CONFIG_KERNEL
#define TASK_SCHEDULER_DISABLED (0)
	 
//#if defined(CONFIG_INIC) || (CONFIG_USBD)
//#undef  DWC_HOST_ONLY
//#undef  DWC_DEVICE_ONLY
//#define DWC_DEVICE_ONLY	1
//#else
//#undef  DWC_DEVICE_ONLY
//#undef  DWC_HOST_ONLY
//#define DWC_HOST_ONLY 1
//#define CONFIG_USB_HOST_ONLY 1
//#endif
